# ===============================================================================
# This is the main site-wide playbook. It includes common provisioning tasks
# as well as individual system playbooks for specific server roles.
# USE WITH CAUTION: Modifying this file can impact the entire infrastructure.
# It's the whole magilla.

---

# Refresh SSH host keys on the controller before connecting to any hosts.
- name: Refresh SSH host keys (controller)
  hosts: all
  gather_facts: false
  become: false
  tags: always
  tasks:
    - name: Check SSH connectivity from controller
      ansible.builtin.wait_for:
        host: "{{ ansible_host | default(inventory_hostname) }}"
        port: 22
        timeout: 5
      register: ssh_connectivity_check
      failed_when: false
      changed_when: false
      delegate_to: localhost
      run_once: false

    - name: Scan current host keys
      ansible.builtin.command:
        argv:
          - ssh-keyscan
          - -T
          - "5"
          - -t
          - rsa,ecdsa,ed25519
          - "{{ ansible_host | default(inventory_hostname) }}"
      register: ssh_keyscan_result
      changed_when: false
      delegate_to: localhost
      run_once: false
      when: not ssh_connectivity_check.failed

    - name: Ensure current host keys are present
      ansible.builtin.known_hosts:
        name: "{{ ansible_host | default(inventory_hostname) }}"
        key: "{{ item }}"
        state: present
      loop: >-
        {{
          ssh_keyscan_result.stdout_lines
          | reject('match', '^#')
          | reject('equalto', '')
          | list
        }}
      delegate_to: localhost
      run_once: false
      when:
        - not ssh_connectivity_check.failed
        - ssh_keyscan_result.stdout_lines | length > 0

# Common Server Provisioning
- name: Ubuntu 24.04 Common Provisioning Tasks
  hosts: linux_servers
  gather_facts: true
  become: true
  roles:
    - role: provision_ubuntu_2404
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_version == "24.04"
      tags: [provision, system]

# Docker Provisioning
- name: Docker Provisioning Tasks
  hosts: docker
  gather_facts: true
  become: true
  roles:
    - role: docker_engine
      tags: [provision, docker]

# Pi-hole Deployment
- name: Deploy pihole-01 and pihole-02
  hosts: pihole
  become: true
  roles:
    - role: pihole_v6
      tags: [infra, services, dns]
